softeerbootcamp-3rd/Team7-FiveGuys

AOS/app/src/main/res/drawable/icon_arrow_right.xml, AOS/app/src/main/res/layout/fragment_my_page.xml, AOS/app/src/main/res/values/strings.xml
> 마이페이지 레이아웃 구현
<br>
<br>
<br>
https://github.com/softeerbootcamp-3rd/Team7-FiveGuys/assets/116520932/9ce98c3e-8c9b-42e8-a300-33ac3767006a
=> [AOS] 마이페이지 레이아웃 구현

BE/robocar/.gitignore, appspec.yml, scripts/deploy.sh
> CICD 구현 빌드 파일 작성
<br>
<br>
<br>
=> [BE] CICD 구현

AOS/app/src/main/java/org/softeer/robocar/ui/fragment/ReceivedCarPoolRequestDialogFragment.kt, AOS/app/src/main/res/layout/fragment_dialog_received_car_pool_request.xml, AOS/app/src/main/res/values/strings.xml
> 동승 요청(수신) 다이얼로그 레이아웃을 구현했습니다. 
닉네임, 인원 수 textView는 디자인 수정사항을 반영해서 배치했습니다.
close #26 
<br>
<br>
<br>
=> [AOS] 동승 요청(수신) 다이얼로그 레이아웃 구현

AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDialogFragment.kt, AOS/app/src/main/res/layout/fragment_dialog_car_pool_request.xml, AOS/app/src/main/res/values/strings.xml
> 동승 요청(발신) 다이얼로그 레이아웃을 구현했습니다.
close #25 
<br>
<br>
<br>
=> [AOS] 동승 요청(발신) 다이얼로그 레이아웃 구현

AOS/app/src/main/AndroidManifest.xml, AOS/app/src/main/java/org/softeer/robocar/RequestCarPoolActivity.kt, AOS/app/src/main/java/org/softeer/robocar/ui/activity/RequestCarPoolActivity.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/NoAvailableCarPoolFragment.kt, AOS/app/src/main/res/drawable/icon_arrow_left.xml, AOS/app/src/main/res/layout/activity_request_car_pool.xml, AOS/app/src/main/res/layout/fragment_no_available_car_pool.xml, AOS/app/src/main/res/values/strings.xml
> 동승 불가능 레이아웃을 구현했습니다. 
close #20 
<br>
<br>
<br>
공통 activity인 activity_request_car_pool를 구현한 뒤, 해당 activity에 들어갈 동승 불가능 fragment를 구현했습니다.
=> [AOS] 동승 불가능 레이아웃 구현

BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseApi.java, BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java, BE/robocar/src/main/java/com/fiveguys/robocar/controller/GarageController.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/GarageReqDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/entity/Garage.java, BE/robocar/src/main/java/com/fiveguys/robocar/repository/GarageRepository.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/GarageService.java
> Garage 도메인 관련 API (CRUD) 구현
<br>
<br>
<br>
=> [BE] Garage API 구현

BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java, BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtRequestFilter.java, BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java, BE/robocar/src/test/java/com/fiveguys/robocar/util/JwtUtilTest.java
UserId를 id로 수정
> User의 기본키값을 userId 에서 id로 변경하게 되었습니다.
> JWT 부분에 추가로 수정할 부분이 생겨 해당 부분만 수정하고 바로 merge하겠습니다.
<br>
<br>
<br>
* resolve #73
=> [Fix] UserId가 안고쳐진 부분 추가 수정

BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtRequestFilter.java
=> [Fix] JWT 예외 처리 추가

BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java, BE/robocar/src/main/java/com/fiveguys/robocar/config/NaverMapConfig.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/MapService.java, BE/robocar/src/main/java/com/fiveguys/robocar/util/JsonParserUtil.java, BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
> NaverMap 한글주소를 좌표로 변환하는 로직추가
<br>
<br>
<br>
> 안드로이드에서 한글주소로 보내준다고해서 MapService에 지번,도로명주소등 상세 주소를 받으면 좌표로 변환하는 로직 추가하였습니다.
=> [BE] NaverMap 한글주소를 좌표로 변환하는 로직추가

AOS/app/src/main/AndroidManifest.xml, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HeadcountDialogFragment.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt, AOS/app/src/main/res/layout/activity_home.xml, AOS/app/src/main/res/layout/activity_map.xml, AOS/app/src/main/res/layout/fragment_path_setting.xml, AOS/app/src/main/res/navigation/bottom_sheet_nav_graph.xml, AOS/app/src/main/res/navigation/home_nav_graph.xml
> PR(#83) 피드백 반영 및 navigation 수정 (#89)
<br>
<br>
<br>
=> [AOS] PR(#83) 피드백 반영 및 navigation 수정

BE/robocar/src/main/java/com/fiveguys/robocar/controller/UserController.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/UserAvailableResDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/UserService.java
> 안드로이드 측에서 data키 값을 받아야해서 ResponseApi.ok()에 null 값을 추가, DTO생성
=> [Fix] Response data값 수정

AOS/app/src/main/AndroidManifest.xml, AOS/app/src/main/java/org/softeer/robocar/data/dto/user/request/SignUpRequest.kt, AOS/app/src/main/java/org/softeer/robocar/data/dto/user/response/CheckAvailableNicknameResponse.kt, AOS/app/src/main/java/org/softeer/robocar/data/dto/user/response/CheckAvailableUserIdResponse.kt, AOS/app/src/main/java/org/softeer/robocar/data/model/CarPoolType.kt, AOS/app/src/main/java/org/softeer/robocar/data/model/TaxiType.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRemoteDataSource.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRemoteDataSourceImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRepository.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRepositoryImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/service/user/UserService.kt, AOS/app/src/main/java/org/softeer/robocar/di/DataSourceModule.kt, AOS/app/src/main/java/org/softeer/robocar/di/RepositoryModule.kt, AOS/app/src/main/java/org/softeer/robocar/di/ServiceModule.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/CheckDuplicatedNicknameUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/CheckDuplicatedUserIdUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/SignUpUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/ui/activity/LoginActivity.kt, AOS/app/src/main/java/org/softeer/robocar/ui/activity/RegisterActivity.kt, AOS/app/src/main/java/org/softeer/robocar/ui/adapter/SignUpBindingAdapter.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HomeFragment.kt, AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/SignUpViewModel.kt, AOS/app/src/main/res/layout/activity_login.xml, AOS/app/src/main/res/layout/activity_register.xml, AOS/app/src/main/res/navigation/home_nav_graph.xml
> 회원가입 API를 연동했습니다.
<br>
<br>
<br>
=> [AOS] 회원가입 API 연동

BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java, BE/robocar/src/main/java/com/fiveguys/robocar/controller/UserController.java, BE/robocar/src/main/java/com/fiveguys/robocar/converter/CarpoolRegisterParser.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/CarpoolRegisterReqDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/entity/CarpoolRequest.java, BE/robocar/src/main/java/com/fiveguys/robocar/models/CarType.java
Operation에서 carState를 받을 수 있도록 수정
> 동승 등록시 누락되어 있던 carState를 추가
>  CarState Enum추가, 스웨거 문구 수정
<br>
<br>
<br>
> 설명한 부분만 수정했습니다
=> [Fix] CarState Enum 추가, 스웨거 문구 수정

BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/CarpoolRegisterReqDto.java
CarpoolRegisterReqDto의 필드값의 대소문자 오타로 인식이 안되던 버그 수정
=> [Fix] dto 대소문자 오류 수정

AOS/app/build.gradle.kts, AOS/app/src/main/java/org/softeer/robocar/data/dto/route/response/RouteResponse.kt, AOS/app/src/main/java/org/softeer/robocar/data/mapper/RouteInfoMapper.kt, AOS/app/src/main/java/org/softeer/robocar/data/model/Route.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRemoteDataSource.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRemoteDataSourceImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRepository.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRepositoryImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/service/route/RouteService.kt, AOS/app/src/main/java/org/softeer/robocar/di/DataSourceModule.kt, AOS/app/src/main/java/org/softeer/robocar/di/RepositoryModule.kt, AOS/app/src/main/java/org/softeer/robocar/di/ServiceModule.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/GetOptimizedRouteUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt, AOS/app/src/main/java/org/softeer/robocar/ui/adapter/RouteBindingAdapert.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/TaxiInformationFragment.kt, AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/RouteViewModel.kt, AOS/app/src/main/res/layout/activity_map.xml, AOS/app/src/main/res/layout/fragment_taxi_information.xml
> 출발,호스트도착,게스트도착지에 맞게 차량 배정 + 화면
<br>
<br>
<br>
=> [AOS] 출발,호스트도착,게스트도착지에 맞게 차량 배정 + 화면

BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java, BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java, BE/robocar/src/main/java/com/fiveguys/robocar/models/CarType.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java, BE/robocar/src/main/java/com/fiveguys/robocar/util/CreateCarpoolListUpResDto.java, BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java, BE/robocar/src/test/java/com/fiveguys/robocar/service/OperationServiceTest.java
> 10분 이내 거리에 있는 호스트와 매칭. 인원수를 고려하고 정렬순서는 예상 도착시간 기준
<br>
<br>
> 추후 등록
=> [BE] Carpool List Up 구현

BE/robocar/build.gradle, BE/robocar/src/main/java/com/fiveguys/robocar/config/FCMConfig.java, BE/robocar/src/main/java/com/fiveguys/robocar/controller/FcmController.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/CarpoolRequestDTO.java, BE/robocar/src/main/java/com/fiveguys/robocar/models/FcmMessage.java, BE/robocar/src/main/java/com/fiveguys/robocar/models/FcmNotificationType.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/FirebaseCloudMessageService.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/PaymentService.java
> FCM을 통한 push 알림 구현
<br>
<br>
<br>
=> [BE] FCM API 구현

BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserLoginReqDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/UserService.java
Reverts softeerbootcamp-3rd/Team7-FiveGuys#106
=> Revert "[BE] 로그인시 FCM토큰 저장"

BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserLoginReqDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/UserService.java
> 머지가 제대로 수행되지 않아 코드를 재작성 했습니다. 내용은 #106 과 동일합니다
=> [BE] 머지 인식 오류로 User-FCM 코드 재작성

BE/robocar/src/main/java/com/fiveguys/robocar/controller/FcmController.java, BE/robocar/src/main/java/com/fiveguys/robocar/models/FcmMessage.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/FirebaseCloudMessageService.java
> fcm push되는 데이터 및 리턴값 수정
<br>
<br>
<br>
=> [BE] fcm push되는 데이터 및 리턴값 수정

BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserLoginReqDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/UserService.java
> 코드를 직접 재작성하다보니 놓친 부분이 있었습니다. 
작동하는지 테스트까지 완료하고 다시 올립니다
<br>
<br>
<br>
=> [Fix] 토큰 크기 수정, 오류 수정

BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java, BE/robocar/src/main/java/com/fiveguys/robocar/converter/CarpoolRegisterParser.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
> 호스트의 매칭 취소 구현 및 테스트
> 락 부분은 이슈 #114 에서 구현
<br>
<br>
<br>
=> [BE] Operations/Carpools 호스트 매칭 취소

BE/robocar/src/main/java/com/fiveguys/robocar/repository/CarRepository.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/CarService.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
=> [Fix] findAvailableCar 오류 수정

BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/RouteResDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/RouteSoloResDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/repository/CarRepository.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
> 혼자타기 "/operations/optimized-route/solo" 생성
<br>
<br>
<br>
=> [BE] 혼자타기 "/operations/optimized-route/solo" 생성

BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java, BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/OnBoardDto.java, BE/robocar/src/main/java/com/fiveguys/robocar/entity/InOperation.java, BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
>DB 세팅:
>1. inOperation에 컬럼 두개 추가, 둘다 불란형이며 hostOnBoard, guestOnBoard
>2. 처음에는 기본으로 둘다 true
>요청:
>1. 내리는 요청: inOperaionId, id를 받고 False로 전환/ null값 리턴
>2. 확인하는 요청: inOperaionId, id를 받고 확인/불란 리턴
<br>
<br>
* resolve #133
=> [BE] InOperation 탑승 상태 기능 추가

AOS/app/src/main/java/org/softeer/robocar/data/dto/car/CarDetailsResponse.kt, AOS/app/src/main/java/org/softeer/robocar/data/dto/operation/OnboardResponse.kt, AOS/app/src/main/java/org/softeer/robocar/data/mapper/CarDetailsMapper.kt, AOS/app/src/main/java/org/softeer/robocar/data/model/CarDetails.kt, AOS/app/src/main/java/org/softeer/robocar/data/model/Onboard.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/car/CarRemoteDataSource.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/car/CarRemoteDataSourceImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/car/CarRepository.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/car/CarRepositoryImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/onboard/OnboardRemoteDataSource.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/onboard/OnboardRemoteDataSourceImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/onboard/OnboardRepository.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/onboard/OnboardRepositoryImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/service/CarPool/CarPoolService.kt, AOS/app/src/main/java/org/softeer/robocar/data/service/car/CarService.kt, AOS/app/src/main/java/org/softeer/robocar/data/service/operation/OnboardService.kt, AOS/app/src/main/java/org/softeer/robocar/di/DataSourceModule.kt, AOS/app/src/main/java/org/softeer/robocar/di/RepositoryModule.kt, AOS/app/src/main/java/org/softeer/robocar/di/ServiceModule.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/CarDetailsUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/ReceivedCarPoolRequestDialogFragment.kt, AOS/app/src/main/java/org/softeer/robocar/ui/fragment/TaxiInformationFragment.kt, AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MapViewModel.kt, AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/OnboardViewModel.kt, AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/ReceivedCarPoolRequestDialogViewModel.kt, AOS/app/src/main/java/org/softeer/robocar/utils/TimeMillsExtentsions.kt, AOS/app/src/main/res/layout/fragment_taxi_information.xml, AOS/app/src/main/res/navigation/bottom_sheet_nav_graph.xml
> Inoperationid 바탕으로 정보 불러오기
<br>
<br>
<br>
=> [AOS] Inoperationid 바탕으로 정보 불러오기

AOS/app/src/main/java/org/softeer/robocar/data/network/ApiExtensions.kt, AOS/app/src/main/java/org/softeer/robocar/data/network/ApiResult.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRemoteDataSource.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRemoteDataSourceImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRepository.kt, AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRepositoryImpl.kt, AOS/app/src/main/java/org/softeer/robocar/data/service/user/UserService.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/CheckDuplicatedNicknameUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/CheckDuplicatedUserIdUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/domain/usecase/SignUpUseCase.kt, AOS/app/src/main/java/org/softeer/robocar/ui/activity/RegisterActivity.kt, AOS/app/src/main/java/org/softeer/robocar/ui/adapter/SignUpBindingAdapter.kt, AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/SignUpViewModel.kt, AOS/app/src/main/java/org/softeer/robocar/utils/ContextExtensions.kt, AOS/app/src/main/res/layout/activity_register.xml, AOS/app/src/main/res/values/strings.xml
> 네트워크 통신 시 발생하는 예외를 처리합니다.
<br>
<br>
<br>
https://zsmb.co/designing-and-working-with-single-view-states-on-android/
=> [Feat] 회원가입 네트워크 통신 예외 처리
